version: 2
updates:
  # Docker base images
  - package-ecosystem: "docker"
    directory: "/ansible-core/debian-bookworm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/debian-bookworm-slim"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/debian-trixie"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/debian-trixie-slim"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/rockylinux-10"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/ubuntu-22.04"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/ubuntu-24.04"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/ansible-core/ubuntu-26.04"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willhallonline"
    labels:
      - "dependencies"
      - "github-actions"
