# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-alpine:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-alpine-3.6" ansible25/alpine36/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-alpine-3.7" ansible25/alpine37/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-alpine-3.6" ansible25/alpine38/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.6" ansible27/alpine36/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.7" ansible27/alpine37/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-alpine-3.6" ansible27/alpine38/
    - docker push "$CI_REGISTRY_IMAGE"

build-ubuntu:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-ubuntu-16.04" ansible25/ubuntu1604/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-ubuntu-18.04" ansible25/ubuntu1804/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-ubuntu-16.04" ansible27/ubuntu1604/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-ubuntu-18.04" ansible27/ubuntu1804/
    - docker push "$CI_REGISTRY_IMAGE"

build-centos:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.5-centos-7" ansible25/centos7/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.7-centos-7" ansible27/centos7/
    - docker push "$CI_REGISTRY_IMAGE"
